# -*- coding: utf-8 -*-
"""scrape_scire.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xe-4_PtU0Xt5mrEhpQ6CfDg7KXl2RtkX
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import json
import re

# Headers to mimic a browser
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

# Fetch the webpage
url = 'https://scireresearch.com/'
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.text, 'html.parser')
    print("✅ Page fetched successfully!")
else:
    print(f"❌ Failed to fetch page. Status code: {response.status_code}")
    exit()

# 1. Extract Headline
headline = soup.find('h1')
headline_text = headline.text.strip() if headline else "Not found"

# 2. Extract all paragraph text for key sections
paragraphs = soup.find_all('p')
paragraph_texts = [p.text.strip() for p in paragraphs if p.text.strip()]

# 3. Extract Service Highlights
service_sections = soup.find_all(['h2', 'h3', 'strong'])
service_titles = [s.text.strip() for s in service_sections if s.text.strip()]

# 4. IMPROVED: Extract Contact Information
# Look for contact section more thoroughly
contact_info = {}

# Find all text on the page
all_text = soup.get_text()

# Email - search more broadly
email_pattern = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'
email_matches = re.findall(email_pattern, all_text)
email = email_matches[0] if email_matches else "Not found"

# Phone - search for Kenyan phone patterns
phone_patterns = [
    r'\+254\s?\d{3}\s?\d{6}',  # +254 704 813110
    r'\+254\d{9}',              # +254704813110
    r'07\d{2}\s?\d{6}',         # 0712 345678
    r'07\d{8}'                  # 0712345678
]

phone = "Not found"
for pattern in phone_patterns:
    phone_match = re.search(pattern, all_text)
    if phone_match:
        phone = phone_match.group(0)
        break

# Location - look for Nairobi
location = "Not found"
location_match = re.search(r'Nairobi,\s?Kenya', all_text, re.IGNORECASE)
if location_match:
    location = location_match.group(0)
else:
    # Try just Nairobi
    location_match = re.search(r'Nairobi', all_text, re.IGNORECASE)
    if location_match:
        location = location_match.group(0) + ", Kenya"

# 5. Extract "Why Choose Us" points
why_choose_us = []
for p in paragraphs:
    text = p.text.strip()
    if any(keyword in text.lower() for keyword in ['research', 'experience', 'ai', 'certified', 'data']):
        if len(text) > 20:  # Only meaningful sentences
            why_choose_us.append(text)

# Limit to unique points
why_choose_us = list(dict.fromkeys(why_choose_us))[:4]

# 6. Extract "Beyond Research" pillars
beyond_research = []
for strong_tag in soup.find_all('strong'):
    text = strong_tag.text.strip()
    if any(keyword in text for keyword in ['Infrastructure', 'Intelligence', 'Partnerships', 'Data', 'AI']):
        beyond_research.append(text)

# If none found, look for them in headings
if not beyond_research:
    for h2 in soup.find_all(['h2', 'h3']):
        text = h2.text.strip()
        if any(keyword in text for keyword in ['Verified', 'AI-Powered', 'Global', 'Data', 'Infrastructure']):
            beyond_research.append(text)

# 7. Compile all data
scraped_data = {
    "website": url,
    "headline": headline_text,
    "key_paragraphs": paragraph_texts[:10],
    "service_highlights": service_titles[:8],
    "why_choose_us": why_choose_us[:4],
    "beyond_research_pillars": beyond_research[:3],
    "contact_info": {
        "email": email,
        "phone": phone,
        "location": location
    }
}

# 8. Save as JSON
with open('scire_research_data.json', 'w', encoding='utf-8') as f:
    json.dump(scraped_data, f, indent=4, ensure_ascii=False)
print("✅ Data saved to scire_research_data.json")

# 9. Save as CSV
csv_data = {
    'category': [],
    'key': [],
    'value': []
}

for category, items in scraped_data.items():
    if isinstance(items, dict):
        for key, value in items.items():
            csv_data['category'].append(category)
            csv_data['key'].append(key)
            csv_data['value'].append(str(value))
    elif isinstance(items, list):
        for i, item in enumerate(items):
            csv_data['category'].append(category)
            csv_data['key'].append(f'item_{i+1}')
            csv_data['value'].append(str(item))
    else:
        csv_data['category'].append('metadata')
        csv_data['key'].append(category)
        csv_data['value'].append(str(items))

df = pd.DataFrame(csv_data)
df.to_csv('scire_research_data.csv', index=False)
print("✅ Data saved to scire_research_data.csv")

# Display summary
print("\n📊 Scraped Data Summary:")
print(f"  - Headline: {headline_text}")
print(f"  - Email: {email}")
print(f"  - Phone: {phone}")
print(f"  - Location: {location}")
print(f"  - Key Paragraphs: {len(paragraph_texts)}")
print(f"  - Service Highlights: {len(service_titles)}")
print(f"  - Beyond Research Pillars: {len(beyond_research)}")
print(f"  - Why Choose Us Points: {len(why_choose_us)}")

# Preview the data
print("\n📋 Contact Information Found:")
print(json.dumps(scraped_data['contact_info'], indent=2))

# Show a sample of why_choose_us
if why_choose_us:
    print("\n📋 Why Choose Us Sample:")
    for i, point in enumerate(why_choose_us[:3], 1):
        print(f"  {i}. {point[:100]}...")



import json

with open('scire_research_data.json', 'r') as f:
    data = json.load(f)

print("🔍 FULL SCRAPED DATA STRUCTURE:")
print("=" * 50)

print(f"\n📌 Website: {data['website']}")
print(f"📌 Headline: {data['headline']}")

print(f"\n📞 Contact Information:")
for key, value in data['contact_info'].items():
    print(f"  - {key}: {value}")

print(f"\n📝 Key Paragraphs ({len(data['key_paragraphs'])}):")
for i, p in enumerate(data['key_paragraphs'][:5], 1):
    print(f"  {i}. {p[:80]}...")

print(f"\n💡 Service Highlights ({len(data['service_highlights'])}):")
for i, s in enumerate(data['service_highlights'][:6], 1):
    print(f"  {i}. {s}")

print(f"\n✅ Why Choose Us ({len(data['why_choose_us'])}):")
for i, w in enumerate(data['why_choose_us'], 1):
    print(f"  {i}. {w[:100]}...")

